kind: Service 
apiVersion: v1 
metadata:
  name: mysql
  labels:
    app: mysql      
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - nodePort: 30001
      port: 3306
      targetPort: 3306
